### ISSUE TITLE
Runtime-based branch, mem_modify(...) fails

### ISSUE THREAD

**Issue by l04m33** [linzj/gen-trace#5]
我的系统是 3.17.7 x86_64 内核， prctl(...) 报 EINVAL:

```
❯ ./mem_modify_test 
ptrctl fails Invalid argument
mem_modify_test: mem_modify_test.cpp:36: void test(int): Assertion `count == 1' failed.
```

这个系统 [没有YAMA](http://man7.org/linux/man-pages/man2/prctl.2.html) ，是这个原因吗？

**Comment by linzj** [comment]
确实 这里我已经判断是否有PR_SET_PTRACER 这个宏定义的存在
不过看了代码 我发现我没有保存errno即调用write。这里是个错误。

2015-01-10 10:53 GMT+08:00 Kay Zheng notifications@github.com:

**Comment by linzj** [comment]
已经先保存errno再 print。
